Добавил компоненты Button и Spinner
snaxjs/rick-and-morty pull request #1
Opened 2023-08-21 21:12 UTC by GarnagaA

Добавил компонент Spinner
Добавил компонент Button
issue: нужно импортировать заготовленные цвета из src\scss\colors.scss

2023-08-22 07:55 UTC, snaxjs commented on src/components/Button/index.scss
Стили написаны неправильно, смотри примеры стилей в других компонентах

2023-08-22 08:33 UTC, snaxjs requested changes

2023-08-22 08:33 UTC, snaxjs commented on src/components/Button/index.tsx
> +      className={isLoading? 'storybook-button__spinner' : 'storybook-button'}
Неправильно указал стили, читай БЭМ, как указать модификатор.

className={`storybook-button${props.isLoading ? ' storybook-button_loading' : ''}`}

2023-08-22 08:33 UTC, snaxjs commented on src/components/Spinner/index.tsx
> +import './index.scss'
Зачем тут импорт стилей ? Это такой же компонент как и все, импортируй в главный файл стилей в папке components

2023-08-22 08:33 UTC, snaxjs commented on src/components/Spinner/index.tsx
> +interface SpinnerProps {
interface SpinnerProps { 
  styles?: CSSProperties;
}

2023-08-22 08:33 UTC, snaxjs commented on src/components/Spinner/index.tsx
> +const Spinner: FC<SpinnerProps> = ({width, height, margin}) => {
const Spinner = (props: SpinnerProps}) =>

2023-08-22 08:33 UTC, snaxjs commented on src/components/Spinner/index.tsx
> +
Что за отступы ? Настрой prettier в настройках IDE, иначе будет засчитывать изменения при разработке, гит учитывает это, уже 3 раз говорю тебе, prettier выбрать из папки node_modules ЭТОГО проекта, а не у себя где-то там

2023-08-22 08:33 UTC, snaxjs commented on src/components/Button/Button.stories.tsx
> +export const Primary_WithSpinner: Story = {
Внимательно почитай документацию, там можно можно указывать пропсы, нужно удалить этот Primary_WithSpinner и сделать это все в одном Primary

2023-08-22 08:33 UTC, snaxjs commented on src/components/Button/index.tsx
> +import './index.scss';
Убрать импорт

2023-08-22 08:33 UTC, snaxjs commented on src/components/Spinner/index.scss
> +.lds-ring {
компонент называется spinner, класс должен называться spinner, а не lds-ring

2023-08-22 08:33 UTC, snaxjs commented on src/components/Spinner/index.scss
> +@keyframes lds-ring {
spinner-animation, а не lds-ring

2023-08-22 08:33 UTC, snaxjs commented on src/components/Button/index.scss
> +.storybook-button, .storybook-button__spinner {
Стили написаны неправильно, смотри примеры стилей в других компонентах

2023-08-22 08:33 UTC, snaxjs commented on src/components/Button/index.tsx
> +export const Button = ({
Компоненты экспортируются по умолчанию, а не так, смотри как экспортируются другие компоненты

2023-08-23 14:44 UTC, snaxjs commented on src/components/Button/Button.stories.tsx
> +// const meta: Meta<typeof Button> = {
Удали комментарий, не должно быть в проекте такого мертвого кода

2023-08-23 14:44 UTC, snaxjs commented on src/components/Button/Button.stories.tsx
> +// export const Primary_WithSpinner: Story = {
Удали комментарий, не должно быть в проекте такого мертвого кода

2023-08-23 14:44 UTC, snaxjs commented on src/components/Button/index.scss
> +@import "../../scss/colors";
Импорт тут не нужен, цвета импортируются в другом месте и они уже импортированы

2023-08-23 14:44 UTC, snaxjs commented on src/components/Button/index.tsx
>  interface ButtonProps {
Название интерфейсов начинается с буквы I (Interface), т.е. IButtonProps

2023-08-23 14:44 UTC, snaxjs commented on src/components/Button/index.tsx
>  interface ButtonProps {
Во всех компонентах есть пропс classNames?: string[];

2023-08-23 14:44 UTC, snaxjs commented on src/components/Button/index.tsx
> +      className={`storybook-button${
className={classNames(`storybook-button${
        props.isLoading ? " storybook-button__spinner" : ""
      }`, props.classNames)}

classNames импортируется отсюда https://github.com/snaxjs/rick-and-morty/blob/main/src/utils/ClassNames.ts

2023-08-23 14:44 UTC, snaxjs commented on src/components/CharCard/index.scss
> +  justify-content: center;
Невнимательно работаешь с кодом или prettier так и не подключил, что за конченный отступ тут ? Причем даже не в твоём компоненте

2023-08-23 14:44 UTC, snaxjs commented on src/components/Spinner/index.tsx
>  interface SpinnerProps {
ISpinnerProps

2023-08-23 14:44 UTC, snaxjs commented on src/components/Spinner/index.tsx
> +    <div className="spinner" style={props.styles}>
className={classNames(storybook-button${ props.isLoading ? " storybook-button__spinner" : "" }, props.classNames)}

classNames импортируется отсюда https://github.com/snaxjs/rick-and-morty/blob/main/src/utils/ClassNames.ts

2023-08-23 14:44 UTC, snaxjs commented on src/components/Spinner/index.tsx
>  interface SpinnerProps {
Добавь пропс classNames?: string[];

2023-08-24 14:25 UTC, GarnagaA commented on src/components/Button/index.tsx
> +      className={`storybook-button${
Для каких кейсов этот хелпер classNames ?

2023-08-24 14:56 UTC, snaxjs commented on src/components/Button/index.tsx
> +      className={`storybook-button${
Для прокидывания классов как [микс](https://ru.bem.info/methodology/quick-start/#%D0%9C%D0%B8%D0%BA%D1%81)

2023-08-24 14:57 UTC, snaxjs commented on src/components/CharCard/index.scss
> +  justify-content: center;
Должно хватить

2023-08-30 16:49 UTC, snaxjs approved these changes

2023-08-30 16:55 UTC, merged